feat : 新增部分FIleSystem的ut
ExplosionEngine/Explosion pull request #123
Opened 2021-08-11 14:08 UTC by Reve4Mevol

2021-08-11 16:22 UTC, FlyAndNotDown requested changes

2021-08-11 16:22 UTC, FlyAndNotDown commented on Common/FileSystem/CMakeLists.txt
> +file(GLOB_RECURSE DEMO_SOURCES Sample/*.cpp)
Sample 为啥要链 googletest？

2021-08-11 16:22 UTC, FlyAndNotDown commented on Common/FileSystem/Include/FileSystem/Entry.h
> +        [[nodiscard]] bool IsExists()
const，下面能加的也看下

2021-08-11 16:22 UTC, FlyAndNotDown commented on Common/FileSystem/Include/FileSystem/Entry.h
> +        [[nodiscard]] bool IsExists()
const

2021-08-11 16:22 UTC, FlyAndNotDown commented on Common/FileSystem/Include/FileSystem/Entry.h
> +            return *this;
这里不需要 return 吧

2021-08-12 16:13 UTC, Reve4Mevol commented on Common/FileSystem/CMakeLists.txt
> +file(GLOB_RECURSE DEMO_SOURCES Sample/*.cpp)
复制粘贴多了

2021-08-12 16:13 UTC, Reve4Mevol commented on Common/FileSystem/Include/FileSystem/Entry.h
> +            return *this;
我看网上的例子好像都有

2021-08-16 17:30 UTC, FlyAndNotDown approved these changes

2021-08-16 17:31 UTC, FlyAndNotDown commented
先给你合入了，后续 UT 继续补充

2021-08-16 17:31 UTC, merged