Added Vulkan Buffer.
ExplosionEngine/Explosion pull request #163
Opened 2022-02-21 16:19 UTC by bluesky013

2022-02-21 16:50 UTC, FlyAndNotDown requested changes

2022-02-21 16:50 UTC, FlyAndNotDown commented on Engine/RHI/Sample/Triangle.cpp
> +            delete device;
有 device.Destroy() 吧，没有的话加一下，直接 delete 不太行，或者先不写销毁逻辑，后面统一加

2022-02-22 15:08 UTC, bluesky013 commented on Engine/RHI/Sample/Triangle.cpp
> +            delete device;
OK

2022-02-22 15:19 UTC, FlyAndNotDown approved these changes

2022-02-22 15:19 UTC, merged