add vk dynamic rendering and validation layers, fix some validation errors
ExplosionEngine/Explosion pull request #208
Opened 2022-08-27 06:23 UTC by SakuragiHnmch

2022-08-27 09:22 UTC, FlyAndNotDown requested changes

2022-08-29 06:39 UTC, SakuragiHnmch commented on Engine/Source/RHI-Vulkan/Src/Device.cpp
> +        "VK_KHR_depth_stencil_resolve",
这两个扩展不加vaidation layer会报错

2022-08-29 13:51 UTC, FlyAndNotDown requested changes

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Include/RHI/Vulkan/Gpu.h
> +        VKInstance* GetInstance() const;
都用引用就行了

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Include/RHI/Vulkan/Instance.h
> +        void PopulateDebugMessengerCreateInfo(vk::DebugUtilsMessengerCreateInfoEXT& createInfo);
这个函数是不是可以 static，或者就这么几行干脆就没必要封函数了

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Src/CommandEncoder.cpp
> +        auto pipeline = dynamic_cast<VKGraphicsPipeline*>(beginInfo->pipeline);
auto*

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Src/CommandEncoder.cpp
> +        auto vkFormat = VKEnumCast<IndexFormat ,vk::IndexType>(mBufferView->GetIndexFormat());
这个逗号格式有问题

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Src/Device.cpp
> +        "VK_KHR_depth_stencil_resolve",
"VK_KHR_depth_stencil_resolve" 和 "VK_KHR_create_renderpass2" 确认下是不是一定需要

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Src/TextureView.cpp
> -        return result;
你这最后少了个默认情况的 return 吧，Clion 应该有报 Warning，看一下

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Src/TextureView.cpp
> +        : TextureView(createInfo), device(dev), vkTexture(tex), vkTextureView(VK_NULL_HANDLE), info(*createInfo)
createInfo 是有可能空指针的，建议不要直接存 CreateInfo，把里面需要的东西拆开来存，构造里 Assert(createInfo != nullptr) 然后挨个拷贝

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI/Include/RHI/TextureView.h
> +        Extent<3> extent;
删掉，从 Texture 里面拿就行了

2022-08-29 13:51 UTC, FlyAndNotDown commented on Engine/Source/RHI/Sample/Triangle.cpp
> +            viewCreateInfo.extent = {width, height, 0};
删掉

2022-08-30 07:33 UTC, SakuragiHnmch commented on Engine/Source/RHI-Vulkan/Src/Device.cpp
> +        "VK_KHR_depth_stencil_resolve",
**Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ] Object 0: handle = 0x7f953c070000, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x12537a2c | Missing extension required by the device extension VK_KHR_dynamic_rendering: VK_KHR_depth_stencil_resolve. The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://vulkan.lunarg.com/doc/view/1.3.216.0/mac/1.3-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)**

**Validation Error: [ VUID-vkCreateDevice-ppEnabledExtensionNames-01387 ] Object 0: handle = 0x7fae59037800, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x12537a2c | Missing extension required by the device extension VK_KHR_depth_stencil_resolve: VK_KHR_create_renderpass2. The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://vulkan.lunarg.com/doc/view/1.3.216.0/mac/1.3-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)**
dynamic rendering 依赖于 depth_stencil_resolve, depth_resolve_stencil依赖于create_renderpass2

2022-08-31 12:50 UTC, FlyAndNotDown approved these changes

2022-09-02 02:36 UTC, closed without merging