vk copy function
ExplosionEngine/Explosion pull request #219
Opened 2022-09-20 06:48 UTC by SakuragiHnmch

2022-09-20 13:16 UTC, FlyAndNotDown requested changes

2022-09-20 13:16 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Include/RHI/Vulkan/Texture.h
> +        VKTextureView* GetTextureView();
Texture 里存 TextureView 是什么操作？

2022-09-20 13:16 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Include/RHI/Vulkan/Common.h
> +    VK_ENUM_MAP_BEGIN(TextureAspect, vk::ImageAspectFlags)
不要直接从 Bits Cast 成 Flags，有现成的函数，GetAspectMask()

2022-09-20 13:16 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Src/CommandEncoder.cpp
> +                texture->GetTextureView()->GetBaseArrayLayer(),
ImageSubresourceLayers 改一下，mipLevels 改成 mipLevels、baseMipLevel，然后再加一下 arrayLayers、baseLayer，都没有 TextureView，更别想着从 texture 里面拿了

2022-09-20 13:16 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Src/CommandEncoder.cpp
> +                srcSubResourceInfo->mipLevels,
同上

2022-09-20 13:16 UTC, FlyAndNotDown commented on Engine/Source/RHI-Vulkan/Src/Texture.cpp
> -        return new VKTextureView(*this, device, createInfo);
同上，这个文件的修改都回退掉

2022-09-26 02:16 UTC, SakuragiHnmch commented on Engine/Source/RHI-Vulkan/Include/RHI/Vulkan/Texture.h
> +    class VKTextureView;
这一行漏删了，下次提交再提上去

2022-09-26 07:36 UTC, FlyAndNotDown approved these changes

2022-09-26 07:36 UTC, merged